### ISSUE TITLE
Voodon Dash Bug

### ISSUE THREAD

**Issue by Jmantheking111** [vret001/KU#73] opened 2022-02-23 04:11 UTC
**Describe the bug**
Voodon is going backwards when I use the Mach rampage while flying

**When did you last experience the issue:**
2/22/2022, 8:34 PM PST

**To Reproduce**
1. Use Voodon 
2. Use Mach Rampage while flying

**Expected behavior**
Voodon will go backward and upwards when using Mach damage while flying instead of going forward

**Screenshots**
None

**Desktop (please complete the following information):**
 - IOS 10.11.6
 - Browser: Chrome

**Additional context**
None

**Comment by vret001** [comment] 2022-02-23 10:13
Duplicate of #57

**Closed by vret001** 2022-02-23 10:13 UTC
