### ISSUE TITLE
Jet Jaguar Beta Teleport Back Bug

### ISSUE THREAD

**Issue by GalllaxyL** [vret001/KU#204] opened 2022-03-11 14:52 UTC
**Describe the bug**
You just teleport back using jet jaguar beta when you use 3.

**When did you last experience the issue:**
Today and everyday.

**To Reproduce**
1. Be with jet jaguar beta.
2. Be atacked using 3 or be a lil unlucky.
3. You made it!

**Expected behavior**
you teleport back on where you.

**Screenshots**

https://user-images.githubusercontent.com/101411241/157890748-4ec5868a-836c-45ef-836c-cdfa752f2b5b.mp4

**Desktop (please complete the following information):**
 - OS: Windowns 11.
 - Browser: Opera GX.

**Additional context**
This is anoying in fights.

**Comment by Zeely-Weely** [comment] 2022-03-26 06:55
Duplicate of #144

**Closed by Zeely-Weely** 2022-03-26 06:55 UTC
