### ISSUE TITLE
Jet Jaguar beta

### ISSUE THREAD

**Issue by TheGamingRhino** [vret001/KU#64] opened 2022-02-22 20:07 UTC
**Describe the bug**
When you use the dash ability it clips through the ground it doesn't walk straight on the ground and this make it to were I get stuck under people and die because of it

**When did you last experience the issues
2/22/22 at 3:01 pm est time zoner

**To Reproduce**

**Expected behavior**
For it not to clip through the ground and and stay on the island and not go under it

**Comment by vret001** [comment] 2022-02-23 10:17
Duplicate of #33

**Closed by vret001** 2022-02-23 10:17 UTC
