### ISSUE TITLE
Charge attacks bug

### ISSUE THREAD

**Issue by Amurgos** [vret001/KU#51] opened 2022-02-21 08:27 UTC
**Describe the bug**
So for example the the third attack on sp jet jaguar, when you attack it basically sinks down the terrain it also happens with femuto and t rodan

**When did you last experience the issue:**
Everytime you use a charge attack

**To Reproduce**
1. Use the charge attacks
2. it starts sinking down
3. Bug
4. You sink down instead if going straight

**Expected behavior**
Charge attacks should go straight not down

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please fix this bug

**Comment by vret001** [comment] 2022-02-21 21:01
Duplicate of #33

**Closed by vret001** 2022-02-21 21:01 UTC
