### ISSUE TITLE
Mechagodzilla 2021’s roars take energy 

### ISSUE THREAD

**Issue by EnternalX** [vret001/KU#82] opened 2022-02-23 22:35 UTC
**Describe the bug**
Everytime I use Mg21’s roar and laugh, it depletes my energy to zero and then I have to wait for it to charge up. Same with the roar and laugh, they take over a minute to charge. The roar takes 40 and the laugh takes 80 energy.

**When did you last experience the issue:**
2/23/21 4:12 PM

**To Reproduce**
1. Use Mg21 and use his roar and laugh

**Expected behavior**
For the roars to not take energy and be the regular roars that take 10 seconds to charge up again.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: IPhone XR
 - OS: IOS 15.3.1
 - Browser: Safari
 - Version: 10

**Comment by vret001** [comment] 2022-02-24 01:13
Duplicate of #75

**Closed by vret001** 2022-02-24 01:13 UTC
