### ISSUE TITLE
Kumonga's Ensnaring Onrush Bug

### ISSUE THREAD

**Issue by VixenSaid** [vret001/KU#47] opened 2022-02-20 22:48 UTC
**Describe the bug**
^
• Kumonga's Ensnaring Onrush attack is very bugged. It doesn't leap as far and high as it should, and pulls you to the ground instead or makes your Kaiju spaz in the air very briefly. It also triggers anti-cheat some of the time which causes your Kaiju to take damage upon jumping.

**When did you last experience the issue**
^
• Around 5:20 P.M.EST, 2/20/22

**To Reproduce**
^
• Steps to reproduce the behavior:

1. Go to the Kaiju menu.
2. Spawn in as Kumonga.
3. Click on Ensaring Onrush.
4. Hop around for a bit. Try paring space bar and Ensaring Onrush for full results.
5. See the error.

**Expected behavior**
^
• I expected to jump cleanly across the terrain as Kumonga should instead of dragging across the ground. Usually when I pair jump with Ensaring Onrush - I go higher and further, but this was not the case.

**Evidence**
^
https://user-images.githubusercontent.com/63977689/154867727-0bba5dd2-a22a-43fc-9630-4a01e07c908b.MOV

**Smartphone**
^
Device: [iPhoneXS Max]
OS: [iOS 15.2.1]
Version [5.3.0]

**Additional context**
^
None, this should be all good.

**Comment by VixenSaid** [comment] 2022-02-20 22:53
I forgot to add that this bug was somewhat present in the Titanus Rodan update - just not has bad as it is now.

**Comment by VixenSaid** [comment] 2022-02-21 19:14
The time here is 5:20 P.M

**Comment by vret001** [comment] 2022-02-21 21:02
Duplicate of #33

**Closed by vret001** 2022-02-21 21:02 UTC
