### ISSUE TITLE
You go underground each time you use anything like a dash 

### ISSUE THREAD

**Issue by Oedds** [vret001/KU#37] opened 2022-02-19 12:35 UTC
**Describe the bug**
When you use something that makes you move forward, such as dash or MUTO/JJB attack, you go underground 

https://user-images.githubusercontent.com/100011435/154801833-50421121-5e77-49f7-8bb3-16f07e84387b.MOV

**When did you last experience the issue:**
Just now 
**To Reproduce**
1. Go to Kaiju Selection
2. Click on MG21, MUTO or JJB
3. Use the rush attacks 

**Expected behavior**
I just expected to attack normally, I don’t know

**Additional context**
Gives no advantage over running or attacking really.

**Comment by vret001** [comment] 2022-02-19 16:31
Duplicate of #33, please report there

**Closed by vret001** 2022-02-19 16:31 UTC
