### ISSUE TITLE
this is so sad

### ISSUE THREAD

**Issue by SocksAreCool** [vret001/KU#151] opened 2022-03-02 12:23 UTC
**Describe the bug**
I have a max Anguirus and I do not have the badge
**When did you last experience the issue:**
When I maxed anguirus
**To Reproduce**

**Expected behavior**
get the badge for maxing anguirus
**Screenshots**
![erggrwgh](https://user-images.githubusercontent.com/100774418/156360872-aeb25c49-9b29-4794-8d84-f70f480e3046.jpg)
![hhh](https://user-images.githubusercontent.com/100774418/156360876-44dae33d-c4bc-4fc7-b8b0-b6728394cb4b.jpg)
![htreeth](https://user-images.githubusercontent.com/100774418/156360878-0308e14d-2b1e-4321-8fac-cff91d91c8d1.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
My Roblox username is socksarecool500 and also i think this glitch affects others cause i refuse to believe that only 635 players have maxed it

**Comment by vret001** [comment] 2022-03-02 15:08
Duplicate of #79

**Closed by vret001** 2022-03-02 15:08 UTC
