### ISSUE TITLE
Behemoth sinks into the ground while doing Primal Clash

### ISSUE THREAD

**Issue by ColWilBald** [vret001/KU#46] opened 2022-02-20 15:01 UTC
**Describe the bug**

Behemoth sinks into the ground for the duration of its second attack, before shooting back up to the surface at the end.

**When did you last experience the issue:**
A date and time

2/20/22

**To Reproduce**

Use Behemoth's Primal Clash move.

**Expected behavior**

For Behemoth to stay on the surface

**Screenshots**

**Desktop (please complete the following information):**

Windows 11, Chrome, 21H2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment] 2022-02-20 17:25
Duplicate of #33

**Closed by vret001** 2022-02-20 17:25 UTC
