### ISSUE TITLE
MG21 dash bug

### ISSUE THREAD

**Issue by EnderReaper16** [vret001/KU#44] opened 2022-02-20 10:17 UTC
**Describe the bug**
This bug has more to do with the dash itself, then the teleport glitch that happens after because of the anti cheat, basically, when you dash with mg21, iv noticed that most of the time you glitch into the ground, and then immediately glitch back onto the floor, this is an issue because sometimes it throws off my aim with rockets, and sometimes even makes them detonate on the ground, it also messes up the hitbox on my stomp, sometimes making the hitbox appear deaper undeneath the map, causing me to miss targets i would normally hit, and its just derpy looking. there is also another bug for this dash where you use the dash, it does the animation, but you dont move at all, tho i dont have video for this one. I'm not sure if this has anything to do with ping or server age

**When did you last experience the issue:**
10:00 20/02/2022, but this issue happens every time I play Mechagodzilla 2021

**To Reproduce**
1. Use Mechagodzilla 2021 (obviously)
2. Use the dash, from what iv noticed, it tends to happen every time i use it, or at least the vast majority of the time,

 **Expected behavior**
i expected for MG21 to dash forwards with the jet rockets and it did, i did not expect for it to glitch into the ground until its knees or elbows

**Screenshots**

**Desktop (please complete the following information):**
 - OS: no idea what this is
 - Browser Opera GX browser
 - Version, i have no idea, but presumably the latest version

https://user-images.githubusercontent.com/100020672/154837931-53f3e969-61c8-44f1-83b5-9365913d4b60.mp4

https://user-images.githubusercontent.com/100020672/154837911-e96e8312-dc51-4ce5-b053-c2f4f2823f01.mp4

**Comment by vret001** [comment] 2022-02-20 17:24
Duplicate of #33

**Closed by vret001** 2022-02-20 17:24 UTC
