### ISSUE TITLE
Mothra's Royal Flash

### ISSUE THREAD

**Issue by Kodukushi** [vret001/KU#60] opened 2022-02-22 17:46 UTC
**Describe the bug**
Mothra's Royal Flash was severely changed, it used to follow perfectly, and it was simple to use. Now, however, it feels stiff, and instead of following like before, it instead does a slight glide forward, instead of going straight in the direction its meant to go, it glides forward whilst going down.

**When did you last experience the issue:**
2/23/2022 | 1:31 AM - UTC + 8 hours

**To Reproduce**

**Expected behavior**
It's hard to define; however, royal flash used to feel simple to use, and it went straight in the direction you wanted the move to go.

**Screenshots**

Present Royal Flash:
https://user-images.githubusercontent.com/100226492/155187858-737db515-26bb-43b1-91ac-be9ab46e67d4.mp4

Past Royal Flash:
https://user-images.githubusercontent.com/100226492/155187880-f44ddf67-4f7e-4942-b0c5-3a5b98d78e0c.mp4

https://user-images.githubusercontent.com/100226492/155187866-91ab375e-20e2-4ff6-b4d8-fa9e3f2b2384.mp4

I am on a Windows 11 HP Laptop

**Additional context**
My description may serve to be lackluster, but I've  been using Mosura for around 2 weeks before the rebalance, and started playing today again, and the difference between how Royal Flash works is as clear as night and day.

**Comment by vret001** [comment] 2022-02-24 01:13
Duplicate of #33

**Closed by vret001** 2022-02-24 01:13 UTC
Labels: bug, Affects gameplay
