### ISSUE TITLE
Rpo Mecha godzilla roars

### ISSUE THREAD

**Issue by LMarkPlayz** [vret001/KU#71] opened 2022-02-23 02:16 UTC
**Describe the bug**
its another roar bug with rpo mecha godzilla it takes so long for the cooldown both r and t roar cooldown for rpo too long

**When did you last experience the issue:**
i forgot since i don't really use rpo

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment] 2022-02-23 10:15
Duplicate of #75

**Closed by vret001** 2022-02-23 10:15 UTC
