### ISSUE TITLE
MechaGodzilla 2021 Dash getting caught by anticheat

### ISSUE THREAD

**Issue by Challenger455** [vret001/KU#207] opened 2022-03-12 21:42 UTC
**Describe the bug**
About 20% of the time you use Mecha G's Dash ability it rubberbanded you back with the anticheat, so not only do you get launched back into thermos pulse you take extra damage and get 2 tapped.

**When did you last experience the issue:**
Saturday March 12

**What kaijus does this affect:**
- Mecha G

**To Reproduce**
1. Select Mecha G
2. Use the boost

**Expected behavior**
To get a boost forward and not get rubberbanded back and take large amounts of damage

**Screenshots**
On console so can't

**Device Information**
 - Device: Xbox 1S

**Comment by Zeely-Weely** [comment] 2022-03-26 06:52
Duplicate of #144

**Closed by Zeely-Weely** 2022-03-26 06:52 UTC
