### ISSUE TITLE
Female Muto Plague Escalation teleport bug

### ISSUE THREAD

**Issue by OzenBoozen** [vret001/KU#265] opened 2022-03-29 09:27 UTC
**Describe the bug**
Female Muto will randomly teleport back to where she was when using Plague Escalation

**When did you last experience the issue:**
March 29th 10:23 AM

**To Reproduce**
1. Use Female Muto
2. Press 4
3. Randomly teleport back to where you started when using the skill

**Expected behavior**
I expect to not teleport lmao

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: No idea

**Smartphone (please complete the following information):**
 - Device:

**Additional context**
Buff Millennium Godzilla thank you

**Comment by Zeely-Weely** [comment] 2022-04-10 01:39
Duplicate of #144.

**Closed by Zeely-Weely** 2022-04-10 01:39 UTC
Labels: Bug, Affects gameplay
