### ISSUE TITLE
Heisei Rodan sliding around (in the air and on land) while idle

### ISSUE THREAD

**Issue by Sylvester696969** [vret001/KU#160] opened 2022-03-03 17:30 UTC
The last time the bug happened: 
was yesterday, 3/2/22

how to recreate the issue: 
spawn anywhere as Heisei Rodan (I've learned location doesn't matter, but preferably Tokyo/Prometia so you can land on a building and see the sliding clearer)
Fly up to a building and land on it (You'll slowly start to slide off)

how to recreate the flying issue:
spawn as Heisei Rodan (area does not matter)
fly into the air and stop once you get to any height, you'll slowly start to slide up/down wherever you are in the sky

**Comment by vret001** [comment] 2022-03-03 17:59
Duplicate of #114

**Closed by vret001** 2022-03-03 17:59 UTC
