### ISSUE TITLE
Final Wars Godzilla issue

### ISSUE THREAD

**Issue by maluis** [vret001/KU#141] opened 2022-03-01 07:15 UTC
Username: loco84
Issue time and date: 3/1/2022 (United states) 2:00 - 2:02 am
Issue description: Final Wars Godzilla doesn't want to walk with his two legs apparently. He also keeps going up in the air and takes damage.
Steps to reproduce issue: Spawn in Final Wars Godzilla. As shown in the pictures, I stayed perfectly still and let the game do its thing.
Pictures:
![evidence](https://user-images.githubusercontent.com/55112120/156122287-f1dd4926-981a-42f9-86e0-c307681516c6.png)
![evidence2](https://user-images.githubusercontent.com/55112120/156122305-faf49deb-6ebe-48ec-8c55-d8802ed68c86.png)
:

**Comment by vret001** [comment] 2022-03-01 23:58
Duplicate of #5

**Closed by vret001** 2022-03-01 23:58 UTC
