### ISSUE TITLE
Max dest emblem problem

### ISSUE THREAD

**Issue by MrMamacita** [vret001/KU#77] opened 2022-02-23 14:21 UTC
**Describe the bug**
Well, i was playing like i usually do, with dest at level 99, I was about to max it, and then when I did, I dont know why I didnt get the emblem of it, in the game, it is assumed that when you max destoroyah, you get an emblem of it and even shows in your roblox's profile, but for me, it doesnt appear and have already try to join other servers and reloading the page to solve the problem but still the same.

**When did you last experience the issue:**
23/February/2022 and 6:53 A.M

**To Reproduce**
1. I guess you get into the game, it may only happen when is about max destoroyah, u select him and started playing
2. after getting enough XP for maxing, it gets max
3. and suppoted to get the emblem of it and even check it in roblox's profile
4. See error (it doesnt appear)

**Expected behavior**
Getting the emblem of it (dest)

**Screenshots**

![2022-02-23 (2)](https://user-images.githubusercontent.com/100293326/155337232-b4baf50a-17d8-479a-bf98-36d12bd5a392.png)

![2022-02-23](https://user-images.githubusercontent.com/100293326/155337381-619b439d-60ff-4f18-bdb5-ec121483a73f.png)

**Comment by vret001** [comment] 2022-02-23 16:51
Duplicate of #79

**Closed by vret001** 2022-02-23 16:51 UTC
