### ISSUE TITLE
Voodon and Kumonga being broken

### ISSUE THREAD

**Issue by Kiryu1390** [vret001/KU#57] opened 2022-02-22 14:42 UTC
Voodon's dash being broken and Kumonga's dance and attacks being broken. Voodon: while on the ground he goes through the floor. while flying he goes up instead of going forward. Kumonga: The Ensnaring Onrush does not go forward enough to reach the other player and while using control lock it does not follow the attack just stays where its at. as for the dance it it does not moth side to side.

**Comment by vret001** [comment] 2022-02-24 01:13
Duplicate of #33

**Closed by vret001** 2022-02-24 01:13 UTC
Labels: bug, Affects gameplay
