### ISSUE TITLE
Anticheat dashes are still occuring, I'm using a kiryu and it's still here.

### ISSUE THREAD

**Issue by Reset355341** [vret001/KU#194] opened 2022-03-08 10:25 UTC
**Describe the bug**

**When did you last experience the issue:**
A date and time 3/8/22
16:25 PM

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Zeely-Weely** [comment] 2022-03-26 06:56
Duplicate of #144

**Closed by Zeely-Weely** 2022-03-26 06:56 UTC
