### ISSUE TITLE
Showa Kumonga

### ISSUE THREAD

**Issue by Rqinbxws** [vret001/KU#55] opened 2022-02-22 02:47 UTC
**Describe the bug**
Kumonga Is very unusable, any move you do with it, it takes away your health with the anti-cheat. Also, the dance cuts away over 1k health due to the anti-cheat 

**When did you last experience the issue:**
2/21/2022 9:00Pm Est 

**To Reproduce**
1. Pick Showa Kumonga 
2.  Press v, In order to do the dance
3. Takes away health
**Expected behavior**
You lose over 1k hp. 

**To Reproduce**
1. Pick Showa Kumonga 
2.  Use the 3 attack 
3. May have a Chance to go under the ground
**Expected behavior**
You have a slight chance to go underground 

**To Reproduce**
1. Pick Showa Kumonga 
2.  Use the 2nd attack 
3. Does No damage to my knowledge 
**Expected behavior**
Every time I used this attack, it did no dmg 

**Screenshots**
(https://medal.tv/games/roblox/clips/bV4NWDEm7RVKY/d1337AlLelnB?invite=cr-MSxCcDgsNTUyOTk1Niw) 

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser Chrome 
 - Version Latest erison 

**Additional context**
Kumonga Is unusable.

**Comment by vret001** [comment] 2022-02-22 05:56
Duplicate of #32

**Closed by vret001** 2022-02-22 05:56 UTC
