### ISSUE TITLE
Mg21s roar is bugged

### ISSUE THREAD

**Issue by ONSFIW** [vret001/KU#74] opened 2022-02-23 09:48 UTC
**Describe the bug**
Mg21s roar lowers the energy alot and has a very long cooldown

Feb 21 6:54 Pm

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment] 2022-02-23 10:13
Duplicate of #67

**Closed by vret001** 2022-02-23 10:13 UTC
