### ISSUE TITLE
Muto third and fourth atck

### ISSUE THREAD

**Issue by petemine** [vret001/KU#45] opened 2022-02-20 11:27 UTC
**Describe the bug**
When i use third atck i sink litle to ground and when i use forth same thing hepend but sometiems it teleport me back to original position and dmg me litle

**When did you last experience the issue:**
20.2.2022 12:15

**Comment by vret001** [comment] 2022-02-20 17:24
Duplicate of #33

**Closed by vret001** 2022-02-20 17:24 UTC
