### ISSUE TITLE
Spawn Damage

### ISSUE THREAD

**Issue by Cipherzi11a** [vret001/KU#198] opened 2022-03-10 00:38 UTC
**Describe the bug**
Right as I spawn in I will take damage after falling down, even if there are no other player’s around. (As if it was fall damage). 

**When did you last experience the issue:**
March 9. 22 6:30 PM

**To Reproduce**
It is seemingly random and only happens right when you spawn in with any Kaiju. 

**Expected behavior**
As you load in you fall down from above like normal, but either as you hit the ground or right before you do you take about half a quarter of damage to your health. 

**Screenshots**
The only thing that would be shown is some damage on the Kaiju.

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 

**Additional context**
Since I use Destoroyah and Shin the most right now it happens to the most with them, but I don’t use other Kaiju enough to know if it happens to everyone.

**Comment by Zeely-Weely** [comment] 2022-03-26 06:55
Duplicate of #144

**Closed by Zeely-Weely** 2022-03-26 06:55 UTC
