### ISSUE TITLE
MZ can fly while useing his ruinous thunder

### ISSUE THREAD

**Issue by ObungaRequiresToes** [vret001/KU#48] opened 2022-02-20 22:54 UTC
**Describe the bug**
MZ can fly while using ruinous thunder

**When did you last experience the issue:**
2/20/2022 11:52

**To Reproduce**
use your t roar and spam 5

**Expected behavior**
MZ will use ruinous thunder but will also be able to fly

**Screenshots**
https://streamable.com/d5k5n1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 97.0

**Comment by VixenSaid** [comment] 2022-02-20 23:46
To add onto this report real quick. This works with both Tempest Stir, Storm Braver, and can be used to move with Draconian Tempest, or more hilariously - used to move with Concentration _(which you gain no Inner Storm from while moving)_. These are done with the same **roar + ability immediately after** process. It's a fun bug to try, but ultimately should get removed due to being able to abuse it.

**Comment by vret001** [comment] 2022-02-22 06:00
Duplicate of #26

**Closed by vret001** 2022-02-22 06:00 UTC
