### ISSUE TITLE
Mosura. Mg21, Femuto and other's Tp back and take Dmg

### ISSUE THREAD

**Issue by HumanityFailsUs** [vret001/KU#52] opened 2022-02-21 10:27 UTC
**Describe the bug**
Everytime One of Femuto runs, Mg21 boosts, Mosura Flings with Royal Flash, I mostly get Tped back to where i first begin the attack and take 1000 damage
**When did you last experience the issue:**
A date and time
21/02/22 9:22PM EAST
**To Reproduce**
1. Choose any kaiju with a Running, boosting or flinging ability (femuto, mg21 ext.)
2. Click on the Boost, fling attack
3. Its a random chance you get flung back, Happened to me twice in a row

**Expected behavior**

**Screenshots**
Not able to get video up

**Comment by vret001** [comment] 2022-02-21 21:00
Duplicate of #32

**Closed by vret001** 2022-02-21 21:00 UTC
