### ISSUE TITLE
Voodons Melee attacks bugged

### ISSUE THREAD

**Issue by Jelliotts** [vret001/KU#50] opened 2022-02-21 04:25 UTC
**Describe the bug**
(There are multiple) 
-Voodon while standing still, using the attack "Puppet Rage" instead of having the normal wing slap animation it now acts as if you are moving while doing it. When using the "Mach Rampage" attack with Voodon on the ground, Voodon will now start running down into the ground instead of going straight forward. Voodon with the same attack (Mach Rampage) while flying will go straight upwards downwards or even just backwards at random.

**When did you last experience the issue:**
Date: 2/20/2022, Time: 10:15 Pm CST

**To Reproduce**
1. Go the the Kaiju Select Menu 
2 Play As Voodon
3. Use the Attack "Puppet Rage" on the ground and "Mach Rampage" in the air

**Expected behavior**
- (Puppet Rage) I expect for Voodon to use the right animation and have the correct hitboxes while not moving on the ground.
-(Mach Rampage) with this attack I expect Voodon to go straight forward like normal instead of going in the opposite direction

**Screenshots**
https://user-images.githubusercontent.com/100108958/154888576-de4ab6c3-a4b7-4901-a26c-512c38978606.mp4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  chrome, 
 - Version [

**Additional context**
none

**Comment by vret001** [comment] 2022-02-22 17:30
I'm told the effects from Puppet Rage are intentional, though Mach Rampage is not working as intended, so that will be fixed in the next update. Thanks for the report

**Comment by Jelliotts** [comment] 2022-02-22 18:45
what happens with Puppet rage is that it hits correctly but the animation is wrong. before Voodon would do 2 wing slaps forward and a bite while standing still but now it does the animations of him flying/walking instead of the not moving animation.

**Comment by vret001** [comment] 2022-03-02 00:07
This has been fixed.

**Closed by vret001** 2022-03-02 00:07 UTC
Labels: Bug, Affects gameplay
