### ISSUE TITLE
Roar animation not playing, animations playing before sounds and effects with beams and pulses

### ISSUE THREAD

**Issue by KUsussy** [vret001/KU#232] opened 2022-03-22 23:32 UTC
**Describe the bug**

**When did you last experience the issue:**
A date and time

**To Reproduce**
1. Pressing the attack buttons2. 
2. Either not playing animation or animation playing before the effect and sound

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [ipad 11]
 - Browser [safari]

**Additional context**
Add any other context about the problem here. Could be from the roblox update.

**Comment by GojiratheKing** [comment] 2022-03-23 01:31
This bug will only occur a with a few monsters, and some have it worse or better than others.
Heisei and Burning can pulse then dash to do thousands of damage nearly instantly without warning, while Burning and MZ's beam is heavily delayed. Shin and Megalon have it as far as I've heard but I haven't tested it yet.
This bug should be fixed ASAP due to how Burning and Heisei can abuse it, burning can do 3.2k damage instantly with meltdown.

https://user-images.githubusercontent.com/100480443/159604113-ceaef615-920e-4539-af1c-ed344cbc4842.mp4

**Comment by AllstarPlayz** [comment] 2022-03-23 01:53
Just a little extra info, at least for the beams, it's happening for every kaiju.

**Comment by Zeely-Weely** [comment] 2022-03-26 07:11
Thank you for these reports! This issue was caused by Roblox and has already been fixed, though I'll keep the report open for a little longer in case any more show up.

**Closed** 2022-04-09 23:18 UTC
Labels: Bug, Affects gameplay, Roblox issue, Fixed In Next Update
