### ISSUE TITLE
Heisei Rodan Flying Bug

### ISSUE THREAD

**Issue by ThatGuy2134** [vret001/KU#120] opened 2022-02-26 16:03 UTC
**Describe the bug**
When Im flying with heisei rodan and then go in this way ↗️ I just start auto flying I dont touch anything and rodan slowly moves

**When did you last experience the issue:**
26.02.2022 
4:46 PM

**To Reproduce**
1.Take rodan and spawn anywhere
2. Fly up and make rodan face this way ↗️ (same goes with ↖️)
3.And boom rodan auto fly

**Expected behavior**
To fix this bug or problem

**Screenshots**
I have only video.

**Additional context**
I dont think so there is any

https://user-images.githubusercontent.com/100481650/155849801-bf9be52a-07a5-45b2-8136-766dc52f16ce.mp4

**Comment by vret001** [comment] 2022-03-02 00:02
Duplicate of #114

**Closed by vret001** 2022-03-02 00:02 UTC
Labels: Bug
