### ISSUE TITLE
Bug Issue with Monster Zero and Godzilla Ultima AOE dmg (alpha roar and Release Mist)

### ISSUE THREAD

**Issue by YellowMonsterkilla10** [vret001/KU#17] opened 2022-02-18 12:25 UTC
Describe the bug:
Monster Zero and Ultima Godzilla AOE attacks dmg seems to be rather randomized at somepoint doing only lower than their Max AOE dmg. Heres the Example, MZ Alpha roar AOE max dmg can do 375 but sometime another usage of the alpha roar it can do 50 dmg or lower. For Ultima its same as MZ sometime you do the the max dmg or the lower dmg etc.

When did you last experience the issue:
February 18th, 2022 9:30 UTC

To Reproduce:
Select Monster Zero or Ultima Godzilla
Repetitive usage of of their AOE attacks (Alpha Roar and Release Mist)

Expected behavior:
Was expecting their AOE dmg at always their Max.
Ultima godzilla AOE dmg: 225
monster zero AOE dmg: 375

Additional context:
Ultima Godzilla AOE dmg bug has actully came in framework update. (december 29th Update 5.0.2)
For Monster zero AOE dmg bug i am not sure when the bug came.

Screenshots: (Note the MZ and Ultima i used were only full dmg skill point no other skill point used, only max dmg)

https://user-images.githubusercontent.com/99962562/154679685-05268e62-b0d2-4302-af17-9492908417e7.mp4

https://user-images.githubusercontent.com/99962562/154680699-6fb88928-e8b5-42b9-8134-6f1dc87aa3ea.mp4

Desktop (please complete the following information):

OS: Windows
Browser: Microsoft Edge
Version: 11

Smartphone (please complete the following information):
N/A

**Comment by vret001** [comment] 2022-02-19 08:52
This may be intended behavior, I will follow up with zeel to figure it out. Thanks for the report!

**Comment by vret001** [comment] 2022-02-20 17:26
This was distance falloff based on where you spawned at, the wrong option was chosen for the attack, so the falloff was based on the wrong location. Thank you for the bug report, this should be fixed in the next update.

**Comment by vret001** [comment] 2022-02-22 06:00
This should be fixed in the latest update. Please let us know if this issue still occurs.

**Closed by vret001** 2022-02-22 06:00 UTC
Labels: bug
