### ISSUE TITLE
Please fix lagbacks, cuz it made me custom team, making me a clear suspect

### ISSUE THREAD

**Issue by Faadae** [vret001/KU#43] opened 2022-02-20 04:29 UTC
**Describe the bug**

**When did you last experience the issue:**
A date and time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vret001** [comment] 2022-02-20 06:32
Duplicate of #32

**Closed by vret001** 2022-02-20 06:32 UTC
